
server:
  name: "Relic-Factions"
  discord: "discord.gg/relic-factions"
  website: "relic-factions.com"
  store: "store.relic-factions.com"
  color:
    primary: GOLD
    secondary: YELLOW
  map:
    number: 1
    start-date: "5/16/25"

eotw:
  time: 1 # minutes
  koth: EOTW # the koth to be auto-started once EOTW commences

listeners:
  place-in-combat: true
  starting-timer: true
  disable-enderchest: true
  experience:
    furnace-multiplier: 1.0
    fishing-multiplier: 1.0

research:
  lose-points-on-unlock: false

limiters:
  entity:
    per-chunk: 25
  world-border: 2944
  nether-border: 2000
  end-border: -1
  enchants:
    - PROTECTION;2
    - SHARPNESS;2
    - KNOCKBACK;0
    - FIRE_ASPECT;0
    - POWER;4

combat:
  allow-end-portal-enter: false

commands:
  combat:
    type: DENY
    commands:
      - "tree"
  freeze-allowed:
    - "msg"
    - "message"
    - "whisper"
    - "w"
    - "pm"
    - "tell"
    - "r"
    - "reply"

timers:
  starting: 3600
  pvp: 1800
  combat: 30
  home: 10
  stuck: 150
  enderpearl: 16
  apple: 10
  gapple: 21600
  lff: 120
  request: 300
  report: 300
  logout: 30
  bardeffect: 5
  jumpeffect: 15
  speedeffect: 15
  backstab: 15
  archermark: 10

economy:
  type: en-US
  default-balance: 500

deathban:
  default-time: 120
  times:
    DonatorOne: 90
    DonatorTwo: 75
    DonatorThree: 60

koth:
  time: 15 # minutes
  on-capture:
    - say %player% (%faction%) has just captured %koth%!

conquest:
  time: 30 # seconds
  points-per-cap: 5
  points-loss-per-death: 0
  max-points: 250
  on-capture:
    - say %player% (%faction%) has just captured %conquest%!

mountain:
  reset-time: 2 # minutes

elo:
  enable: true
  points-on-kill: 10
  points-on-death: 10
  koth:
    enable: true
    points-on-win: 25
  conquest:
    enable: true
    points-on-win: 25

elevators:
  sign: true
  minecart: true

factions:
  dtr:
    max: 5.5
    multiple: 1.01
    death: 1.0
    regen: # time in minutes
      start-delay: 60
      delay: 3
      increment: 0.03
  map-radius: 64
  home:
    nether: 20
    end: 30
    disable-in-end: false
  claim:
    buffer:
      distance: 3
      type: RED_STAINED_GLASS
    price:
      multiplier: 250
      selling-multiplier: 0.5
      per-block: 0.25
  sizes:
    worlds:
      default:
        warzone-build-limit: 300
        warzone: 750
      nether:
        warzone-build-limit: 80
        warzone: 200
  members:
    max: 10
  name:
    min: 3
    max: 15
    blocked:
      - "MINEHQ"
      - "VELTPVP"
      - "ARCANE"
  allies:
    max: 1
    attacking:
      prevent: true
      damage-multiplier: 0.5

scoreboard:
  title: "%primary%&l%servername% &7| &fMap %map-number%"
  lines:
    - "&7&m-------------------------"
    - "%customtimers%"
    - "&a&lSale&7: &c%server_sale_timer%<display=%has_server_sale_timer%"
    - "&a&lKey Sale&7: &c%server_keysale_timer%<display=%has_server_keysale_timer%"
    - "&b&lKey All&7: &c%server_keyall_timer%<display=%has_server_keyall_timer%"
    - "&6&l%active_class%<display=%has_active_class%"
    - " &7* &eEnergy&7: &f%bard_energy%<display=%player_is_bard%"
    - " &7* &eEffect&7: &f%player_bardeffect_timer%<display=%has_player_bardeffect_timer%"
    - " &7* &eSpeed&7: &f%player_speedeffect_timer%<display=%has_player_speedeffect_timer%"
    - " &7* &eJump&7: &f%player_jumpeffect_timer%<display=%has_player_jumpeffect_timer%"
    - " &7* &eBackstab&7: &f%player_backstab_timer%<display=%has_player_backstab_timer%"
    - "&a&lStarting&7: &c%player_starting_timer%<display=%has_player_starting_timer%"
    - "&a&lPvP Timer&7: &c%player_pvp_timer%<display=%has_player_pvp_timer%"
    - "&9&lHome&7: &c%player_home_timer%<display=%has_player_home_timer%"
    - "&5&lEnderpearl&7: &c%player_enderpearl_timer%<display=%has_player_enderpearl_timer%"
    - "&6&lApple&7: &c%player_apple_timer%<display=%has_player_apple_timer%"
    - "&6&lGApple&7: &c%player_gapple_timer%<display=%has_player_gapple_timer%"
    - "&6&lArcher Tag&7: &c%player_archermark_timer%<display=%has_player_archermark_timer%"
    - "&c&lSpawn Tag&7: &c%player_combat_timer%<display=%has_player_combat_timer%"
    - "&a&lSOTW&7: &c%server_sotw_timer%<display=%has_server_sotw_timer%"
    - "&c&lEOTW&7: &c%server_eotw_timer%<display=%has_server_eotw_timer%"
    - "&4&lLogout&7: &c%player_logout_timer%<display=%has_player_logout_timer%"
    - "&4&lStuck&7: &c%player_stuck_timer%<display=%has_player_stuck_timer%"
    - "%mod-lines%"
    - "%conquest-lines%"
    - "%koth-lines%"
    - "%mountain-lines%"
    - "%focus-lines%"
    - "&7&m-------------------------"
  mod-mode:
    - "&6&lStaff Mode"
    - " &7* &eVanished: &c%vanished%"
    - " &7* &eGamemode: &c%gamemode%"
    - " &7* &eBypass: &c%modmode-bypass%<display=%has_permission_relic.command.mod.bypass%"
    - " &7* &eOnline: &f%online%"
  focus:
    - "&6&lFocus"
    - " &7* &eFaction&7: &r%faction%"
    - " &7* &eHome&7: &r%home%"
  conquest:
    header: "&e&lConquest&7:"
    no-scores: "  &7No scores yet"
    score: "  &e%faction%&7: &c%points%"
  koth:
    normal: "&9&l%koth%&7: &c%time%"
    special: "&5&l%koth%&7: &c%time%"
    eotw: "&c&l%koth%&7: &c%time%"
  mountain:
    line: "&d&l%type%&7: &c%time%"

kits:
  archer:
    enabled: true
    multiplier: 1.25
    speed:
      item: SUGAR
      effect: SPEED
      duration: 160
      amplifier: 3
    jump:
      item: FEATHER
      effect: JUMP_BOOST
      duration: 140
      amplifier: 6
  bard:
    enabled: true
    effect-range: 20
    max-energy: 100
    click-effects-combat: true
    hold-effects-in-spawn: true
    click-effects-in-spawn: false
    items:
      strength_hold:
        name: Strength I
        item: BLAZE_POWDER
        energy: 0
        hold: true
        effect: STRENGTH
        duration: 100
        amplifier: 0
        applyOnBard: false
        otherFaction: false
      resistance_hold:
        name: Resistance I
        item: IRON_INGOT
        energy: 0
        hold: true
        effect: RESISTANCE
        duration: 100
        amplifier: 0
        applyOnBard: true
        otherFaction: false
      jumpboost_hold:
        name: Jump Boost II
        item: FEATHER
        energy: 0
        hold: true
        effect: JUMP_BOOST
        duration: 100
        amplifier: 1
        applyOnBard: true
        otherFaction: false
      speed_hold:
        name: Speed II
        item: SUGAR
        energy: 0
        hold: true
        effect: SPEED
        duration: 100
        amplifier: 1
        applyOnBard: true
        otherFaction: false
      fireres_hold:
        name: Fire Resistance I
        item: MAGMA_CREAM
        energy: 0
        hold: true
        effect: FIRE_RESISTANCE
        duration: 100
        amplifier: 0
        applyOnBard: true
        otherFaction: false
      regen_hold:
        name: Regeneration I
        item: GHAST_TEAR
        energy: 0
        hold: true
        effect: REGENERATION
        duration: 160
        amplifier: 0
        applyOnBard: true
        otherFaction: false
      strength_click:
        name: Strength II
        item: BLAZE_POWDER
        energy: 45
        hold: false
        effect: STRENGTH
        duration: 110
        amplifier: 1
        applyOnBard: true
        otherFaction: false
      resistance_click:
        name: Resistance II
        item: IRON_INGOT
        energy: 40
        hold: false
        effect: RESISTANCE
        duration: 110
        amplifier: 1
        applyOnBard: true
        otherFaction: false
      jumpboost_click:
        name: Jump Boost VII
        item: FEATHER
        energy: 20
        hold: false
        effect: JUMP_BOOST
        duration: 110
        amplifier: 6
        applyOnBard: true
        otherFaction: false
      speed_click:
        name: Speed III
        item: SUGAR
        energy: 30
        hold: false
        effect: SPEED
        duration: 110
        amplifier: 2
        applyOnBard: true
        otherFaction: false
      wither_click:
        name: Wither I
        item: SPIDER_EYE
        energy: 40
        hold: false
        effect: WITHER
        duration: 110
        amplifier: 0
        applyOnBard: false
        otherFaction: true
      regen_click:
        name: Regeneration II
        item: GHAST_TEAR
        energy: 35
        hold: false
        effect: REGENERATION
        duration: 110
        amplifier: 1
        applyOnBard: true
        otherFaction: false
  miner:
    enabled: true
    invis-level: 20
  rogue:
    enabled: true
    speed:
      item: SUGAR
      effect: SPEED
      duration: 160
      amplifier: 4
    jump:
      item: FEATHER
      effect: JUMP_BOOST
      duration: 140
      amplifier: 6

features:
  deathbans: true
  staff-chat: true
  report: true
  notes: true
  request: true
  msg: true
  hidden-safezone-players: false
  autosmelt: true
  scoreboard:
    enabled: true
    line-limit: 2