
server:
  name: "Relic-Factions"
  discord: "discord.gg/relic-factions"
  website: "relic-factions.com"
  store: "store.relic-factions.com"
  color:
    primary: GOLD
    secondary: YELLOW
  map:
    number: 1
    start-date: "5/16/25"

limiters:
  world-border: 2944
  nether-border: 2000
  end-border: -1
  enchants:
    - PROTECTION;2
    - SHARPNESS;2
    - KNOCKBACK;0
    - FIRE_ASPECT;0
    - POWER;4

combat:
  allow-end-portal-enter: false

commands:
  freeze-allowed:
    - "msg"
    - "message"
    - "whisper"
    - "w"
    - "pm"
    - "tell"
    - "r"
    - "reply"

timers:
  starting: 3600
  pvp: 1800
  combat: 30
  home: 10
  enderpearl: 16
  apple: 10
  gapple: 21600
  lff: 120
  request: 300
  report: 300
  logout: 30

economy:
  type: en-US
  default-balance: 500

deathban:
  default-time: 120
  times:
    DonatorOne: 90
    DonatorTwo: 75
    DonatorThree: 60

factions:
  dtr:
    max: 5.5
    multiple: 1.01
    death: 1.0
    regen: # time in minutes
      start-delay: 60
      delay: 3
      increment: 0.03
  map-radius: 64
  home:
    nether: 20
    end: 30
    disable-in-end: false
  claim:
    buffer: RED_STAINED_GLASS
    price:
      multiplier: 250
      selling-multiplier: 0.5
      per-block: 0.25
  sizes:
    worlds:
      default:
        warzone-build-limit: 300
        warzone: 750
      nether:
        warzone-build-limit: 80
        warzone: 200
  members:
    max: 10
  name:
    min: 3
    max: 15
    blocked:
      - "MINEHQ"
      - "VELTPVP"
      - "ARCANE"

scoreboard:
  title: "%primary%&l%servername% &7| &fMap %map-number%"
  lines:
    - "&7&m-------------------------"
    - "%customtimers%"
    - "&a&lSale&7: &c%server_sale_timer%<display=%has_server_sale_timer%"
    - "&a&lKey Sale&7: &c%server_keysale_timer%<display=%has_server_keysale_timer%"
    - "&b&lKey All&7: &c%server_keyall_timer%<display=%has_server_keyall_timer%"
    - "&a&lStarting&7: &c%player_starting_timer%<display=%has_player_starting_timer%"
    - "&a&lPvP Timer&7: &c%player_pvp_timer%<display=%has_player_pvp_timer%"
    - "&9&lHome&7: &c%player_home_timer%<display=%has_player_home_timer%"
    - "&5&lEnderpearl&7: &c%player_enderpearl_timer%<display=%has_player_enderpearl_timer%"
    - "&6&lApple&7: &c%player_apple_timer%<display=%has_player_apple_timer%"
    - "&6&lGApple&7: &c%player_gapple_timer%<display=%has_player_gapple_timer%"
    - "&c&lSpawn Tag&7: &c%player_combat_timer%<display=%has_player_combat_timer%"
    - "&a&lSOTW&7: &c%server_sotw_timer%<display=%has_server_sotw_timer%"
    - "&4&lLogout&7: &c%player_logout_timer%<display=%has_player_logout_timer%"
    - "%mod-lines%"
    - "&7&m-------------------------"
  mod-mode:
    - "&6&lStaff Mode"
    - " &7* &eVanished: &c%vanished%"
    - " &7* &eGamemode: &c%gamemode%"
    - " &7* &eBypass: &c%modmode-bypass%<display=%has_permission_relic.command.mod.bypass%"
    - " &7* &eOnline: &f%online%"

features:
  scoreboard:
    enabled: true
    line-limit: 2