
server:
  name: "Relic-Factions"
  discord: "discord.gg/relic-factions"
  website: "relic-factions.com"
  store: "store.relic-factions.com"
  color:
    primary: GOLD
    secondary: YELLOW
  map:
    number: 1
    start-date: "5/16/25"

limiters:
  world-border: 2944

timers:
  starting: 3600
  pvp: 1800
  combat: 30
  home: 10
  enderpearl: 16
  apple: 10
  gapple: 21600
  lff: 120

economy:
  type: en-US
  default-balance: 500

factions:
  map-radius: 64
  home:
    nether: 20
    end: 30
    disable-in-end: false
  claim:
    buffer: RED_STAINED_GLASS
    price:
      multiplier: 250
      selling-multiplier: 0.5
      per-block: 0.25
  sizes:
    worlds:
      default:
        warzone-build-limit: 300
        warzone: 750
      nether:
        warzone-build-limit: 80
        warzone: 200
  members:
    max: 10
  name:
    min: 3
    max: 15
    blocked:
      - "MINEHQ"
      - "VELTPVP"
      - "ARCANE"

scoreboard:
  title: "%primary%&l%servername% &7| &fMap %map-number%"
  lines:
    - "&7&m-------------------------"
    - "&a&lStarting&7: &c%player_starting_timer%<display=%has_player_starting_timer%"
    - "&9&lHome&7: &c%player_home_timer%<display=%has_player_home_timer%"
    - "&5&lEnderpearl&7: &c%player_enderpearl_timer%<display=%has_player_enderpearl_timer%"
    - "&6&lApple&7: &c%player_apple_timer%<display=%has_player_apple_timer%"
    - "&6&lGApple&7: &c%player_gapple_timer%<display=%has_player_gapple_timer%"
    - "&c&lSpawn Tag&7: &c%player_combat_timer%<display=%has_player_combat_timer%"
    - "&7&m-------------------------"

features:
  scoreboard:
    enabled: true
    line-limit: 2