
server:
  name: "Relic-Factions"
  color:
    primary: GOLD
    secondary: YELLOW
  map:
    number: 1
    start-date: "5/16/25"

timers:
  starting: 3600
  pvp: 1800
  combat: 30
  home: 10
  enderpearl: 16
  apple: 10
  gapple: 21600

economy:
  type: en-US
  default-balance: 500

factions:
  claim:
    buffer: RED_STAINED_GLASS
    price:
      multiplier: 250
      selling-multiplier: 0.5
      per-block: 0.25
  sizes:
    worlds:
      default:
        warzone-build-limit: 300
        warzone: 750
      nether:
        warzone-build-limit: 80
        warzone: 200
  members:
    max: 10
  name:
    min: 3
    max: 15
    blocked:
      - "MINEHQ"
      - "VELTPVP"
      - "ARCANE"