name: Relic-Factions
description: A hardcore Minecraft factions plugin where player factions compete for dominance by capturing and defending powerful relics, controlling resource points, and advancing unique tech trees
version: 1.0.0
api-version: 1.21
author: Sub
main: me.sub.RelicFactions.Main.Main
depend:
  - Vault
commands:
  faction:
    aliases:
      - f
      - team
      - t
  balance:
    aliases:
      - bal
  hcf:
    description: Debug command
  timer:
    description: Timer command
  economy:
    aliases:
      - eco
  help:
    description: Help
  filter:
    description: Filter
  lives:
    description: Lives
  lff:
    description: LFF
  pvp:
    description: PvP
  coords:
    description: Coords
  ping:
    description: Ping
  sotw:
    description: SOTW
  gamemode:
    aliases:
      - gm
      - gma
      - gmc
      - gmsp
      - gms
  teleport:
    aliases:
      - tp
  tphere:
    description: TPHere
  staffchat:
    aliases:
      - sc
      - staff-chat
  vanish:
    aliases:
      - v
  modmode:
    aliases:
      - h
  invsee:
    aliases:
      - inspect
  freeze:
    description: Freeze
  fly:
    description: Fly
  panic:
    description: Panic
  report:
    description: Report
  request:
    description: Request
  logout:
    description: Logout
  heal:
    description: Heal
  feed:
    description: Feed
  pay:
    description: Pay
  spawner:
    description: Spawner
  world:
    description: World
  playtime:
    description: Playtime
  toggleglobalchat:
    aliases:
      - tgc
  reply:
    aliases:
      - r
  message:
    aliases:
      - msg
      - pm
      - tell
      - whisper
      - w
  revive:
    description: Revive
  settings:
    description: Settings
  profile:
    description: Profile
  clearinventory:
    aliases:
      - clear
      - ci