name: Relic-Factions
description: A hardcore Minecraft factions plugin where player factions compete for dominance by capturing and defending powerful relics, controlling resource points, and advancing unique tech trees
version: 1.0.0
api-version: 1.21
author: Sub
main: me.sub.RelicFactions.Main.Main
depend:
  - Vault
commands:
  faction:
    aliases:
      - f
      - team
      - t
  balance:
    aliases:
      - bal
  hcf:
    description: Debug command
  timer:
    description: Timer command
  economy:
    aliases:
      - eco
  help:
    description: Help
  filter:
    description: Filter